name: continuous integration (run tests)

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
          pip check
      - name: pytest
        run: |
          pytest -v -m "not webtest"
